#!/usr/bin/env bash

FRAMES_DIR=$(mktemp -d)
DURATION=3.26
FPS=33.3333

timecut "$PWD/../88x31.svg" \
	-W 88 -H 31 -V 88,31 \
	--fps "$FPS" \
	--duration "$DURATION" \
	--screenshot-type png \
	--frame-cache "$FRAMES_DIR" \
	--keep-frames \
	--unrandomize 0 \
	--no-round-to-even-height

pngDir="$FRAMES_DIR"/$(ls "$FRAMES_DIR")

# pngFiles=( "$pngDir"/*.png )
# convert \
# 	-delay $[100/50] \
# 	-loop 0 "${pngFiles[@]}" "$PWD/../88x31.gif"

ffmpeg \
	-y \
	-f image2 \
	-framerate "$FPS" \
	-pattern_type glob -i "$pngDir/*.png" \
	-filter_complex "[0:v] split [a][b];[a] palettegen [p];[b][p] paletteuse" "$PWD/../88x31.gif"

rm -r "$FRAMES_DIR"
rm video.mp4
